version: "3"

services:

  fdk-dataset-harvester:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/fdk-dataset-harvester:test
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - HARVEST_ADMIN_ROOT_URL=https://admin-api.staging.fellesdatakatalog.digdir.no
    ports:
      - "8081:8080"

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"

  fdk-sparql-service:
    image: eu.gcr.io/digdir-fdk-infra/fdk-sparql-service:latest
    ports:
      - "3030:8080"

  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
