openapi: 3.0.2
info:
  title: FDK dataset harvester
  description: Tilgjengeliggjør datasettbeskrivelser fra en datasetkatalog ihht DCAT-AP-NO v2.0
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://fellesdatakatalog.digdir.no'
    email: fellesdatakatalog@digdir.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
tags:
  - name: dcat-ap-no-catalogs
    description: DCAT-AP-NO catalogs
  - name: dcat-ap-no-datasets
    description: DCAT-AP-NO datasets
  - name: sparql
servers:
  - url: 'https://datasets.fellesdatakatalog.digdir.no'
    description: Produksjonsmiljø
  - url: 'https://datasets.staging.fellesdatakatalog.digdir.no'
    description: Testmiljø
  - url: 'https://datasets.demo.fellesdatakatalog.digdir.no'
    description: Demomiljø
paths:
  /catalogs:
    get:
      tags:
        - dcat-ap-no-catalogs
      description: Returns a collection of catalogs
      operationId: getCatalogs
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
  '/catalogs/{id}':
    get:
      tags:
        - dcat-ap-no-catalogs
      description: Returns a catalog
      operationId: getCatalogById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
        '404':
          description: Dataset catalog with requested id does not exist
  '/datasets/{id}':
    get:
      tags:
        - dcat-ap-no-datasets
      description: Returnerer et datasett
      operationId: getDatasetById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
        '404':
          description: Dataset with requested id does not exist
  /sparql/select:
    get:
      description: "Endpoint for perforimg SPARQL queries against FDK's datasets, returns result in a string table or json reply format"
      summary: "Query FDK's datasets with SPARQL SELECT"
      tags:
        - sparql
      responses:
        '200':
          description: OK. The query was executed succsessfully and returned data
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    head:
                      vars:
                        - org
                        - count
                    results:
                      bindings:
                        - org:
                            type: uri
                            value: 'https://data.brreg.no/enhetsregisteret/api/enheter/974760673'
                          count:
                            type: literal
                            value: '10'
            text/plain:
              schema:
                type: string
              example: '---------------------------------------------------------------------------------- | id                                                              | count        | ================================================================================== | "https://data.brreg.no/enhetsregisteret/api/enheter/974760673"  |   643        | ----------------------------------------------------------------------------------'
        '204':
          description: "OK. The query was executed succsessfully but did not return any data"
        '400':
          description: "Bad Request. Attempt to execute a malformed query, other sparql operations than ASK, or non-sparql queries"
      operationId: get-sparql-select
      parameters:
        - schema:
            type: string
          in: query
          name: query
          description: url encoded SPARQL SELECT query
  /sparql/ask:
    get:
      description: "Endpoint for perforimg SPARQL ASK queries against FDK's datasets, returns a boolean indicating whether a query pattern matches or not"
      summary: "Query FDK's datasets with SPARQL ASK"
      tags:
        - sparql
      responses:
        '200':
          description: "OK. The query was executed successfully and returned data"
        '204':
          description: "No Content. The query was executed successfully but did not return any data"
        '400':
          description: "Bad Request. Attempt to execute a malformed query, other sparql operations than ASK, or non-sparql queries"
      operationId: get-sparql-ask
  /sparql/describe:
    get:
      description: "Endpoint for perform SPARQL DESCRIBE queries against FDK's datasets, returns a single result RDF graph containing RDF data about resources"
      summary: "Query FDK's datasets with SPARQL DESCRIBE"
      tags:
        - sparql
      responses:
        '200':
          description: "OK. The query was executed succsessfully and returned data"
        '204':
          description: "No Content. The query was executed succsessfully but did not return any data"
        '400':
          description: "Bad Request. Attempt to execute a malformed query, other sparql operations than DESCRIBE, or non-sparql queries"
      operationId: get-sparql-describe
  /sparql/construct:
    get:
      description: "Endpoint for perforimg SPARQL CONSTRUCT queries against FDK's datasets, returns  a single RDF graph specified by a graph template"
      summary: "Query FDK's datasets with SPARQL CONSTRUCT"
      tags:
        - sparql
      responses:
        '200':
          description: "OK. The query was succsessfully executed and returned"
        '204':
          description: "No Content. The query was executed succsessfully but did not return any data"
        '400':
          description: "Bad Request. Attempt to execute a malformed query, other sparql operations than CONSTRUCT, or non-sparql queries"
      operationId: get-sparql-construct
