logging:
  level.root: ERROR
  level.no.brreg: ERROR
  level.no.difi: INFO
  level.no.dcat: DEBUG
  level.org.springframework: ERROR
  level.org.springframework.web: ERROR
  level.org.elasticsearch: WARN
application:
  httpUsername: ${themesHttpUsername:user}
  httpPassword: ${themesHttpPassword:password}
  referenceDataUrl: ${referenceDataUrl:http://reference-data:8080}
  notificationMailSenderAddress: ${emailSenderAddress:fdksystembjg@gmail.com}
  openDataEnhet: ${openDataEnhet:https://data.brreg.no/enhetsregisteret/api/enheter/}
  harvestRecordRetentionDays: ${harvestRecordRetentionDays:1000}
crawler:
  threadPoolSize: 2
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
fuseki:
  dcatServiceUri: ${dcatServiceUri:http://fuseki:8080/fuseki/dcat}
  adminServiceUri: ${adminServiceUri:http://fuseki:8080/fuseki/admin}
spring:
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:admin}
    password: ${RABBIT_PASSWORD:admin}
  mail:
    host: smtprelay.brreg.no

---
spring:
  profiles: develop, unit-integration

  mail:
    host: smtp.gmail.com
    port: 587
    username: fdksystembjg
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
