logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
fuseki:
  datasetUri: ${FDK_FUSEKI_SERVICE_URI:http://fdk-fuseki-service:8080/fuseki}/dataset-harvest
  metaUri: ${FDK_FUSEKI_SERVICE_URI:http://fdk-fuseki-service:8080/fuseki}/dataset-meta
application:
  datasetUri: ${FDK_DATASET_HARVESTER_URI:https://datasets.staging.fellesdatakatalog.digdir.no}/datasets
  catalogUri: ${FDK_DATASET_HARVESTER_URI:https://datasets.staging.fellesdatakatalog.digdir.no}/catalogs
  harvestAdminRootUrl: ${HARVEST_ADMIN_ROOT_URL:http://fdk-harvest-admin:8080/api}
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

---
spring:
  profiles: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
fuseki:
  datasetUri: http://localhost:3030/fuseki/dataset-harvest
  metaUri: http://localhost:3030/fuseki/dataset-meta
application:
  harvestAdminRootUrl: https://admin-api.staging.fellesdatakatalog.digdir.no/api

---
spring:
  profiles: contract-test
  rabbitmq:
    host: ${WIREMOCK_TEST_HOST}
    port: ${WIREMOCK_TEST_PORT}
    username: admin
    password: admin
application:
  harvestAdminRootUrl: ${WIREMOCK_TEST_URI}/api
  datasetUri: ${WIREMOCK_TEST_URI}/datasets
  catalogUri: ${WIREMOCK_TEST_URI}/catalogs
