logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena.riot: ERROR
server:
  port: 8080
fuseki:
  datasetsGraphUri: ${FDK_FUSEKI_SERVICE_URI:http://fdk-fuseki-service:8080/fuseki}/harvested?graph=datasets
application:
  datasetUri: ${FDK_DATASET_HARVESTER_URI:https://datasets.staging.fellesdatakatalog.digdir.no}/datasets
  catalogUri: ${FDK_DATASET_HARVESTER_URI:https://datasets.staging.fellesdatakatalog.digdir.no}/catalogs
  harvestAdminRootUrl: ${HARVEST_ADMIN_ROOT_URL:http://fdk-harvest-admin:8080/api}
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/datasetHarvester?authSource=admin&authMechanism=SCRAM-SHA-1

---
spring:
  profiles: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/datasetHarvester?authSource=admin&authMechanism=SCRAM-SHA-1
fuseki.datasetsGraphUri: http://localhost:3030/fuseki/harvested?graph=datasets
application:
  harvestAdminRootUrl: https://admin-api.staging.fellesdatakatalog.digdir.no/api

---
spring:
  profiles: contract-test
  rabbitmq:
    host: localhost
    port: 5000
    username: admin
    password: admin
application:
  harvestAdminRootUrl: http://localhost:5000/api
  datasetUri: http://localhost:5000/datasets
  catalogUri: http://localhost:5000/catalogs
fuseki.datasetsGraphUri: http://localhost:5000/fuseki/harvested?graph=datasets
server.port: 5555