apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-dataset-harvester
  name: fdk-dataset-harvester
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: fdk-dataset-harvester
status:
  loadBalancer: {}