apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-dataset-harvester
  name: fdk-dataset-harvester
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-dataset-harvester
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: fdk-dataset-harvester
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"  
    spec:
      containers:
        - name: fdk-dataset-harvester
          image: fdk-dataset-harvester
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
