---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fdk-dataset-harvester-deployment.yaml
  - fdk-dataset-harvester-service.yaml
images:
  - name: fdk-dataset-harvester
    newName: eu.gcr.io/digdir-fdk-infra/fdk-dataset-harvester
    newTag: $(GIT_COMMIT_SHA)
