logging:
  level.root: ERROR
  level.no.brreg: ERROR
  level.no.difi: INFO
  level.no.dcat: DEBUG
  level.org.springframework: ERROR
  level.org.springframework.web: ERROR
  level.org.elasticsearch: WARN
application:
  httpUsername: ${themesHttpUsername:user}
  httpPassword: ${themesHttpPassword:password}
  referenceDataUrl: ${referenceDataUrl:http://reference-data:8080}
  notificationMailSenderAddress: fdksystembjg@gmail.com
  openDataEnhet: https://data.brreg.no/enhetsregisteret/api/enheter/
  harvestRecordRetentionDays: ${harvestRecordRetentionDays:1000}
crawler:
  threadPoolSize: 2
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
fuseki:
  dcatServiceUri: http://fuseki:8080/fuseki/dcat
  adminServiceUri: http://fuseki:8080/fuseki/admin

---
spring:
  profiles: prod
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  mail:
    host: smtprelay.brreg.no
application:
  notificationMailSenderAddress: ${emailSenderAddress}

---
spring:
  profiles: develop, unit-integration

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: fdksystembjg
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true

fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin
application:
  referenceDataUrl: http://localhost:8112
  notificationMailSenderAddress: fdksystembjg@gmail.com

elastic:
  clusterNodes: localhost:9300
  clusterName: elasticsearch
server:
  port: 8107

---
spring:
  profiles: docker
  mail:
    host: smtp.gmail.com
    port: 587
    username: fdksystembjg
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
application:
  notificationMailSenderAddress: fdksystembjg@gmail.com
